version: '3.3'
services:
  postgres:
    image: 'postgres:13.2'
    ports:
      - "5432:5432"
    networks:
      - app_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stocklytics
    volumes:
      - ./docker-postgresql-data-for-dev:/var/lib/postgresql/data
  redis:
    image: 'redis:6.2.1'
    ports:
      - "6379:6379"
    networks:
      - app_net
    volumes:
      - ./docker-redis-data-for-dev:/data

networks:
  app_net:
    driver: bridge